### ISSUE TITLE
Kaloyan Images

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#1]
![residential dashboard](https://user-images.githubusercontent.com/47352943/95991817-843f7300-0e2d-11eb-8066-93d714d936d0.png)

![commercial dashboard](https://user-images.githubusercontent.com/47352943/95992302-1b0c2f80-0e2e-11eb-83b4-218ed73ffa2b.png)

![dashboard max](https://user-images.githubusercontent.com/47352943/95994898-1f861780-0e31-11eb-8e2d-10e5e2650455.png)

![image](https://user-images.githubusercontent.com/47352943/96112184-8ca5b580-0ee2-11eb-9b38-e1b37691feb0.png)

![image](https://user-images.githubusercontent.com/47352943/96121097-dba61780-0eef-11eb-9336-ff235ca13799.png)

![image](https://user-images.githubusercontent.com/47352943/96142538-832c4580-0f02-11eb-8d6f-e9de3898591f.png)

![image](https://user-images.githubusercontent.com/47352943/96143561-7eb45c80-0f03-11eb-811f-e929b54e1d90.png)

**Comment by Masud-Sonday** [comment]
Please advise what the issue is with the dashboard.

**Comment by Masud-Sonday** [comment]
Noted thanks!
