### ISSUE TITLE
Micasa project - Update 3 - Logger Map

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#10]
## Proposed portal enhancements

The logger map is also enhanced to include more detail.  Each pin on the map now includes the additional [dashboard](https://github.com/solarmd-pty-ltd/myPower24-WEB/issues/8) data as specified above (Load, Grid import, Total consumption, Battery %, Active alerts, Load shedding status).  A new feature is to include a RED pin for offline loggers and to reallocate the orange pins to a new function.

- Green pin - Online logger, no active alerts
- Orange pin - Online logger with active alerts
- Red pin - Offline logger

The map should also include a feature to hide / show loggers by status.

https://github.com/solarmd-pty-ltd/myPower24-WEB/projects/2#column-11276887

![image](https://user-images.githubusercontent.com/72873730/96425426-4d39da80-11fc-11eb-9be0-6e487e850008.png)

**Comment by platar86** [comment]
What would be the definition of Loadshedding Status?

**Comment by tiaanv** [comment]
GRID Voltage 0V, or perhaps Inverter warning INVERT INPUT error?
![image](https://user-images.githubusercontent.com/4703398/98464294-8b5a6680-21ca-11eb-8750-99c8d7c2024c.png)

**Comment by tiaanv** [comment]
![image](https://user-images.githubusercontent.com/4703398/98464356-12a7da00-21cb-11eb-9a8b-252b6c108506.png)

This requirement seems to be a merging of the Logger list requirement in #8 where Loadshedding Status is shown.

![image](https://user-images.githubusercontent.com/4703398/98498846-93f58000-2250-11eb-996d-4a831017eb19.png)

**Comment by tiaanv** [comment]
progress?
