### ISSUE TITLE
Sunsynk - time of use/peak based filling device control not complete

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#100]
Hi Team, 

Our sunsynk integration is not 100% complete, the peak based filling is empty.

The system mode screen is effectively the heart of the system & the settings that most users would like to access.

![image](https://user-images.githubusercontent.com/72872833/142988059-f076b9da-50a9-4b5f-a534-dbd0ef1d24a9.png)

Solarman App pulls the data as follows 

![image](https://user-images.githubusercontent.com/72872833/142988356-77ebe403-2182-44d6-a5b0-666b7ca04296.png)

![image](https://user-images.githubusercontent.com/72872833/142988401-eec4332c-d78d-4f35-af88-7340f232a15b.png)

![image](https://user-images.githubusercontent.com/72872833/142988465-5f97324c-e9af-4478-bff4-5015de449fc3.png)

![image](https://user-images.githubusercontent.com/72872833/142988529-fee7a250-a7b1-46c3-b30c-46a6d4923786.png)

If you need an account to check the device control please send a message and I will provide an account.

**Comment by henry-thomas** [comment]
This is ready for testing @KaloyanDi @Kyle-Swanepoel 

Can we get one Sunsynk ready for testing please? @Masud-Sonday if you have time?

**Comment by henry-thomas** [comment]
This has been done for a while, will be in a future logger update if not there already.
