### ISSUE TITLE
Logger V2 - local interfaces not accessible 

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#101]
Hi Team, 

We've had a few clients recently that can't access the local interfaces to add devices.

![image](https://user-images.githubusercontent.com/72872833/142990052-1b943029-2ee6-47c2-83e0-c9a8874082ee.png)

The add device button does not seem to work, so they can only add devices to the interfaces once the logger connects to the server.

Thanks, 
Leonidas

**Comment by henry-thomas** [comment]
LoggerVWeb update is available on server, which should fix this. Logger version >= 8.401
