### ISSUE TITLE
Mypower24 - Axpert & Axpert AI live chart not populating any data

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#102]
Hi Team, 

The live chart under axpert & ai devices are not populating any data.

![image](https://user-images.githubusercontent.com/72872833/142991144-dd94f44a-4d89-4d1b-b01a-f2a416ebbb6e.png)

![image](https://user-images.githubusercontent.com/72872833/142991246-997e8b13-cb2a-4f91-9630-de0c193b6c29.png)

Thanks, 
Leo

**Comment by henry-thomas** [comment]
Added back amcharts3 library temporarily to fix this
