### ISSUE TITLE
Mypower24 - Energy usage tab on dashboard not loading any data

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#103]
Hi Team, 

The energy usage tab on mypower24 is not loading any data.

![image](https://user-images.githubusercontent.com/72872833/142992064-f449f49e-90d0-4263-9393-caea4a3b1439.png)

Environmental & Financial benefits are working.

Thanks, 
Leo

**Comment by henry-thomas** [comment]
Added back the Amcharts3 library in the mean time, pushed to github.
