### ISSUE TITLE
Logger V2 - Local Logger Issues (Urgent) - No devices - production v8.323

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#107]
Local logger (192.168.222.1) - No devices under My Devices.  The logger cannot be commissioned locally, only via Ethernet on the mypower24 portal
![local logger 2](https://user-images.githubusercontent.com/72873730/144985230-23fe8528-1ab3-43c9-9a77-bcf3f73e519a.jpg)

**Comment by henry-thomas** [comment]
Should be fixed with logger update ver > 8.401.
