### ISSUE TITLE
Logger V2 - Local Logger Issues - Offline Loggers - production v8.323

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#108]
Local logger (192.168.222.1) still has offline devices which causes confusion to clients and installers.

![local logger 1](https://user-images.githubusercontent.com/72873730/144985237-b6bfa16a-5b19-47ff-931b-6387ed569146.jpg)

**Comment by henry-thomas** [comment]
Fixed with logger version > 8.401. Need to download local web interface from logger device page. 
![image](https://user-images.githubusercontent.com/60350870/146149879-8e412e56-faef-459c-a595-90fa0621382b.png)
