### ISSUE TITLE
Logger V2 Software Bridge  - Molabo Bridge CAN bus speed

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#109]
The client has requested that the CAN bus speed for the Molabo bridge please be changed to 250k/bits

**Comment by Kyle-Swanepoel** [comment]
Client has followed up with me about the transmission speed change and if it's been completed yet.

**Comment by kamenskiq** [comment]
done, canbus speed changed to 250kbit/s
