### ISSUE TITLE
Micasa project - Update 4 - Logger events

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#11]
## Proposed portal enhancements

The events tab now includes a read and unread function as well as a filtering capability.  The inclusion of the emailing events to designated email addresses is important (please confirm if this function is working as it should).

- An addition for an event for Low Battery - generated when the battery has discharged to the designated value.

https://github.com/solarmd-pty-ltd/myPower24-WEB/projects/2#column-11276887

![image](https://user-images.githubusercontent.com/72873730/96427451-dbaf5b80-11fe-11eb-9d7f-317c1177c41b.png)

**Comment by merlobranco** [comment]
Already implemented, please take a look to the attached screenshots
![Logger Events Mark as read context menu](https://user-images.githubusercontent.com/40404781/105977442-0df01500-609a-11eb-89a7-418ebf154144.PNG)
![Logger Events Read Filtering](https://user-images.githubusercontent.com/40404781/105977445-0f214200-609a-11eb-9634-4f537ae332b7.PNG)

**Comment by tiaanv** [comment]
@merlobranco batter low event? event when battery falls below configured threshold?

**Comment by merlobranco** [comment]
Still working on that

**Comment by tiaanv** [comment]
progress?
