### ISSUE TITLE
Industrial dashboard

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#110]
![Screenshot_20211221-062118_Chrome](https://user-images.githubusercontent.com/47352943/146875072-14160033-0afd-4107-8964-848637b0e0f4.jpg)

- there is no icon for full screen and live chart like the residential dashboard
- battery icon doesn't update state of charge ( full empty)
- dots on battery do not show energy flow ( missing dots)
- environmental data missing

**Comment by platar86** [comment]
please write text in the issue not in the picture.

**Comment by BrilliesNate** [comment]
![image](https://user-images.githubusercontent.com/57934898/149903856-a7817cd1-c643-4f5c-9699-40bb3a63f4d7.png)


Bat Level anim is fixed. 
Full Screen icon fixed.
Environmental Data fixed.

**Comment by BrilliesNate** [comment]
![image](https://user-images.githubusercontent.com/57934898/149904390-13953df2-9cae-4805-bd90-91c29c413bfe.png)
Dot Anim Fixed.
