### ISSUE TITLE
Sunsynk settings

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#112]
![Screenshot_20211221-062652_Chrome](https://user-images.githubusercontent.com/47352943/146871023-bd8ddfc6-2dd1-44df-b3e9-5199b3bc838d.jpg)

-time table from inverter settings is not visible.

**Comment by platar86** [comment]
please write text in the issue not in the picture. Please explain

**Comment by platar86** [comment]
@KaloyanDi please explain this
