### ISSUE TITLE
Cluster data cell temperatures, SOH

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#115]
![Screenshot_20211221-063528_Chrome](https://user-images.githubusercontent.com/47352943/146871757-6894e949-b60d-4438-b30b-15413b0e499f.jpg)

![Screenshot_20211221-063705_Chrome](https://user-images.githubusercontent.com/47352943/146871870-2ca5c961-75fc-4ebe-8a77-f2da545f5277.jpg)

**Comment by platar86** [comment]
please explain this! you have the temperature there we must add SoH only?

**Comment by platar86** [comment]
@KaloyanDi Please Explain! or close this issue

**Comment by KaloyanDi** [comment]
minimum temperature shows 0
