### ISSUE TITLE
Micasa project - Update 5 - Logger branch reporting

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#12]
## Proposed portal enhancements

The client is emphasizing their need to use our reporting function quite heavily.  A lot of what they are asking for is already implemented however there are a few inclusions:

- Consumption total - Implemented already
- Backup power usage - Implemented (Battery discharge)
- Average kW per Sqm - New feature - Sqm obtained from value in [General tab](https://github.com/solarmd-pty-ltd/myPower24-WEB/issues/13)
- Load shedding duration - New feature - Backup power over usage duration

*In addition to this the client requests a report which includes all branches and lists:

- Load - Assuming this would be total consumption
- kWh/Sqm

https://github.com/solarmd-pty-ltd/myPower24-WEB/projects/2#column-11276887

![image](https://user-images.githubusercontent.com/72873730/96430057-fafbb800-1201-11eb-81be-d268f349bd3b.png)

**Comment by tiaanv** [comment]
progress?
