### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#121]
![Screenshot_20211221-065959_Chrome](https://user-images.githubusercontent.com/47352943/146873944-d8ea198e-af92-496e-8b77-b47eb48364f8.jpg)
![Screenshot_20211221-065936_Chrome](https://user-images.githubusercontent.com/47352943/146873953-398e2f18-32a2-4258-9a61-b9855466243b.jpg)

**Comment by henry-thomas** [comment]
Extended JMS timeout for this to not happen
