### ISSUE TITLE
Logger list -right click arrow

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#122]
![Screenshot_20211221-070541_Chrome](https://user-images.githubusercontent.com/47352943/146874936-fc1a7321-27a2-4215-a510-3c2b89ed1e67.jpg)

**Comment by platar86** [comment]
please if possible write inside the 'Issue' text area and point on the pictures. The entire line should be selectable by pressing in the item. It`s a bug that you have to press twice then comes on. We should consider removing that for mobile. Which one of the menu item are you using? 
![image](https://user-images.githubusercontent.com/11694575/147783983-caa0f61e-8127-4c89-a42f-5103c4a456d1.png)
