### ISSUE TITLE
Move bms ex live chart to advanced role ( currently in developer)

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#123]
![Screenshot_20211221-090914_Chrome](https://user-images.githubusercontent.com/47352943/146887149-bb924c2d-c400-4c9e-93ee-9262cf446610.jpg)
![Screenshot_20211221-090914_Chrome](https://user-images.githubusercontent.com/47352943/146887280-b5c00fba-1683-4886-956c-574575b7f07a.jpg)

**Comment by henry-thomas** [comment]
Done, will be for advanced role after next server update.
