### ISSUE TITLE
SunSynk/Goodwe ES Control - Set default charge/discharge algorithm to Dynamic

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#125]
Please change the default charge/discharge algorithm to Dynamic.

![image](https://user-images.githubusercontent.com/72873730/147903429-3186cea3-c102-46c9-97a6-a09bf44fdd0f.png)

**Comment by platar86** [comment]
Done, after version 8.404. And please remember that BMS direct control is supposed to replace this communication.
