### ISSUE TITLE
Mypower24 - EMS does not create device if enabled

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#126]
If EMS Enabled is True, it does not create a virtual device on the logger.

![image](https://user-images.githubusercontent.com/72873730/148511267-60990a29-6368-461d-be0b-228f5e18b2be.png)

![image](https://user-images.githubusercontent.com/72873730/148511295-f6b2f7a2-9dfd-4d58-a246-611b14c90d94.png)

**Comment by platar86** [comment]
Ones is enabled, you can click "Create New Ems Instance" button
