### ISSUE TITLE
Micasa project - Update 6 - Logger general settings

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#13]
## Proposed portal enhancements

The inclusion of 2 new features under the General settings tab.

- Plant sqm - To be entered by the client and used for additional reporting calculations (average consumption per sqm).
- Active check box - Automatically ticked for new loggers but can be unticked for decommissioned loggers and forms part of the filtering in the Logger overview.
 
https://github.com/solarmd-pty-ltd/myPower24-WEB/projects/2#column-11276887

![image](https://user-images.githubusercontent.com/72873730/96432065-aa398e80-1204-11eb-96f1-b76cb5c40191.png)

**Comment by Masud-Sonday** [comment]
@tiaanv Please specify what the ''Active'' check box does.
More precisely please advise what the ''Non active'' state of the button would do in terms of the logger history and visibility.

**Comment by tiaanv** [comment]
@Masud-Sonday. Active is an indicator for reporting purposes.  There are a number of "Consolidated"  reports/"views"(pages). This flag simply includes/excludes the logger from these views/reports.
@Kyle-Swanepoel please share the document that I sent, as well as your interpretations with @Masud-Sonday for insight.  I have attached my original document for reference, and Kyle's response doc
[Logger Portal Enhancements technical feedback 13-10-2020.docx](https://github.com/solarmd-pty-ltd/myPower24-WEB/files/5873326/Logger.Portal.Enhancements.technical.feedback.13-10-2020.docx)
[Interconnect Functional Specification Portal Enchancements V1.0.docx](https://github.com/solarmd-pty-ltd/myPower24-WEB/files/5873327/Interconnect.Functional.Specification.Portal.Enchancements.V1.0.docx)

**Comment by Kyle-Swanepoel** [comment]
@Masud-Sonday The active function unticked would be to decommission a logger.  If the logger were to be replaced.  It would assist in filtering loggers that are in use and those that aren't.  History data would remain as the logger still remains viewable if required.

**Comment by Kyle-Swanepoel** [comment]
https://docs.google.com/document/d/1-4JU_562y7O5xjFoXGB-qqBJ3aJKa-4pqhkshN2Tw2I/edit?usp=sharing

@Masud-Sonday this was the shared document that everyone has access to.
The Github repositories are my responses to the brief based on our offering at the time.

**Comment by tiaanv** [comment]
progress?
