### ISSUE TITLE
DGM Device Alert Icons

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#132]
![image](https://user-images.githubusercontent.com/11694575/150740469-ec846bf2-2262-451d-ad4c-ceacbfcf5938.png)
The icons in the device panel must be the highest alert level exist, in case there is only Info alerts, icon must be same as the one in the dialog.

**Comment by platar86** [comment]
also dialog title says "Alerts for",   all subdevices have field "title"

**Comment by BrilliesNate** [comment]
![Screenshot 2022-01-26 082959](https://user-images.githubusercontent.com/57934898/151116032-cf4df052-e6b3-49d2-8e29-d6e641c8b701.png)
![Screenshot 2022-01-26 082848](https://user-images.githubusercontent.com/57934898/151116054-daad75cb-0034-4557-885e-697ba29fb9fe.png)
![Screenshot 2022-01-26 082920](https://user-images.githubusercontent.com/57934898/151116097-f86d9a81-3f2e-4728-8e11-0e1676363a33.png)
Alerts icons fixed and display is prioritized from Error 1st then warning the info.
Title Fixed to display the device serial number.
