### ISSUE TITLE
No bank-1/bank1-dischargingPower - SLV215442148 

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#134]
Hi Team,

After removing the 2x HV batteries and readding them to the logger, the bank1 power types are not longer generating data in the power manager.

SLV215442148 - 8.404
BMU - fw.146

![image](https://user-images.githubusercontent.com/72873730/154903110-6985286c-e5d8-4282-9577-9ff5142ac9d1.png)

**Comment by platar86** [comment]
please confirm if this is relevant ?

**Comment by Kyle-Swanepoel** [comment]
@platar86 resolved
