### ISSUE TITLE
BMS-EX - Battery Rate Parameters (not a valid number)

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#135]
Hi Team,

Since the update yesterday 21.02.2022 we are not able to update Battery Rated Parameters.

"..not a valid number" 

![image](https://user-images.githubusercontent.com/72873730/155094595-2af2dbda-98d5-4d26-adc6-5c0ef9f65b83.png)

**Comment by henry-thomas** [comment]
Fixed @Kyle-Swanepoel
