### ISSUE TITLE
Actual Values - BMS-EX missing

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#136]
Hi team,

Multiple users experiencing Actual values missing on the BMS-EX device.

![image](https://user-images.githubusercontent.com/72873730/155957336-c31f0d39-f33b-4a4c-a7e3-192f067ebb37.png)

Across all browsers.   Cache has been cleared and still not working.

**Comment by henry-thomas** [comment]
Can you please give us a serial number? After checking a few I can't see this problem.

**Comment by henry-thomas** [comment]
Fixed. Thanks Kyle.

**Comment by Kyle-Swanepoel** [comment]
@henry-thomas Thank you
