### ISSUE TITLE
Logger Scan not working

### ISSUE THREAD

**Issue by henry-thomas** [solarmd-pty-ltd/myPower24-WEB#137]
Link is to login page, not registration.

**Comment by Masud-Sonday** [comment]
Is this Logger QR code scna not working ?

**Comment by henry-thomas** [comment]
@Masud-Sonday we need to confirm. Had someone mention this, so posted here not to forget. 

@Kyle-Swanepoel is this an ongoing issue?

**Comment by BrilliesNate** [comment]
Fixed For new loggers.
