### ISSUE TITLE
Sungrow SC50HV AC information - Incorrect values and units 

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#139]
AC information 
Check and verify AC information such as: phase current, Active Power, Reactive Power and Power Factor
![image](https://user-images.githubusercontent.com/72863064/164407357-99a6ba2b-d6a1-4a47-9711-b48bb7e3d8ea.png)

Check DC information - DC Current showing 0A when charging (displays correct current when discharging)
![image](https://user-images.githubusercontent.com/72863064/164407726-f65f4683-554e-42eb-86fc-128cd4292de7.png)

**Comment by BrilliesNate** [comment]
Fixed. The logic was incorrect in the javascript
