### ISSUE TITLE
Older loggers offline on mypower24

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#14]
Hi,

We've noticed a lot of the old loggers, beginning with B8:27... have not come online since last week Friday.  Many of them are almost always online.  Rebooting the logger also doesn't seem to help.  

Please can we look into this.

Thanks

**Comment by platar86** [comment]
We need one of this logger in R&D

**Comment by Kyle-Swanepoel** [comment]
b8:27:eb:a5:08:5d   (Newlands - Brad Shrimpton)

**Comment by Masud-Sonday** [comment]
This issue was resolved with logger update 7.120.
