### ISSUE TITLE
Sunsynk - residential dashboard doesnt show grid export

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#140]
Logger fw version 8.4072

![image](https://user-images.githubusercontent.com/72863064/165726130-2432d77e-1b80-4431-aea9-758c2f8a2435.png)
![image](https://user-images.githubusercontent.com/72863064/165726343-4eded1f7-2603-48f5-932d-874c3b0ad3ed.png)

**Comment by BrilliesNate** [comment]
Use Factory Dashboard. made some changes so the dashboard factory can work for both residential and  factory.
