### ISSUE TITLE
''Invalid BMS Model'' warning when selecting low voltage BMS EX device

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#142]
login.mypower24.co.za --> My Devices --> Li-ion Storage EX Series

![image](https://user-images.githubusercontent.com/72863064/166662136-90d8efcb-12f6-4748-a8a5-54009be01e38.png)

**Comment by platar86** [comment]
This appear only if you have production permission, this production software is deprecated anyway, please remove all production permission @ bmsex device
