### ISSUE TITLE
BMU ability to change frequency of Sungrow SC630TL-V11

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#145]
BMU should have the ability to increase and decrease the output frequency (independant grid frequency: Register 21) of the Sungrow SC630TL-V11 inverter when its in offgrid mode in order for PV inverters to throttle when the battery cell voltage is high

![image](https://user-images.githubusercontent.com/72863064/169082740-9b7371e1-b683-4ed3-8467-093f469ba34a.png)

**Comment by platar86** [comment]
Done
