### ISSUE TITLE
BMU-H8 - Web page doesnt refresh cell values when clicking on a new battery with a BMS with lower cell count

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#146]
2x BMUs were connected to a logger. 
The 1st BMU, all BMSs are set to the correct cell count of 16.
The 2nd BMU, has a BMS with a cell count of 7.

If the 1st BMU is currently selected, and you select the second BMU, it shows the BMS (with cell count of 7) and fills in the rest of the data (cell 8-16) from the previously selected BMU.

basically it doesnt completely refresh the data if the new selection has missing data.

![image](https://user-images.githubusercontent.com/72863064/169972744-35daab98-c173-40b9-842b-2e75018833ed.png)

**Comment by platar86** [comment]
BMU does not officially support BMS with cell count different than 16
