### ISSUE TITLE
Sungrow SC50HV DC current shows 0A when charging

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#147]
login.mypower24 --> My devices --> Sungrow SC HV Series --> Actual Data --DC Information --> DC Current

Note: when discharging it shows correctly

![image](https://user-images.githubusercontent.com/72863064/170266610-1cae0e80-8aae-4432-b2b5-a2cda967e573.png)

**Comment by BrilliesNate** [comment]
Fixed. Logic wasn't right as the data for charging is - and for discharging it +;
