### ISSUE TITLE
New loggers not updating - 6.600

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#15]
Hi,

Having an issue with new loggers not updating.  The 2 below are stuck on 6.600.  We've tried Soft reboot and System reboot to see if that would assist but it hasn't.

SLV210602816 - Been online 2+ hours.
SLV211614289 - Been online 21 hours. 

Please investigate.

Thanks

**Comment by Kyle-Swanepoel** [comment]
Current list of loggers not updating past 6.600:

SLV205158801
SLV210804401
SLV215548912
SLV213437235
SLV200291123
SLV214619312
SLV210602816
SLV211614289
SLV210499789
SLV209750181

**Comment by Masud-Sonday** [comment]
@Kyle-Swanepoel - Issue has been resolved, please close this issue
