### ISSUE TITLE
BMS-EX - Cluster Settings (Move Controlled Device to Settings Installer tab)

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#150]
Please move the Controlled Device setting to the Settings Installer tab on the BMS-EX so that the installers can set the control device themselves through the logger.
![image](https://user-images.githubusercontent.com/72873730/180953799-2d41e982-b5b4-453b-8676-142ba7e39f05.png)

**Comment by henry-thomas** [comment]
Will be there with the next update.
