### ISSUE TITLE
Production server - alignment issue (BMS Calibration)

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#153]
Hi guys,

The fixed height of 600px on the body is causing a visual issue on the production server with the addition of the new devices.

setting to auto seems to solve it.
![image](https://user-images.githubusercontent.com/72873730/193542581-90ddd85a-3c41-47f4-9ef5-d95d798e6a9a.png)
***
![image](https://user-images.githubusercontent.com/72873730/193542611-1937f909-0fbf-4348-ac61-c7deaa454310.png)

**Comment by BrilliesNate** [comment]
Fixed. Removed fixed width and height.
