### ISSUE TITLE
Temperature sensor missing- clearing via pushbutton on direct comms

### ISSUE THREAD

**Issue by Maritha-v-Loggerenberg** [solarmd-pty-ltd/myPower24-WEB#155]
Would it be possible to disable the external temperature sensors via the push button for direct comms BMSs as most installers now go without loggers.

**Comment by platar86** [comment]
Hi there,
Replacing BMS involve much more settings than just temperature setting. Please consider this scenario in which you have to configure it to send it to the client anyway, why don't you disable it at that time?
Please close this Issue if this can be a solution.

**Comment by Maritha-v-Loggerenberg** [comment]
Do you mean disabling the settings in the factory already?
