### ISSUE TITLE
Packet loss on BMS to inverter for direct comms of LV batteries

### ISSUE THREAD

**Issue by Maritha-v-Loggerenberg** [solarmd-pty-ltd/myPower24-WEB#156]
Can we add a packet loss counter to the Actual Values page of the LV batteries doing direct comms?

**Comment by platar86** [comment]
sure, done 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/11694575/200176136-ac97a4e8-36a4-484b-a0a3-c372f9586d3b.png">

require:
server update 
 loggerVersion:  8.5003
bmsEx version: 184
