### ISSUE TITLE
14.3kWh & Deye Controlled device Comms Failed warning

### ISSUE THREAD

**Issue by Maritha-v-Loggerenberg** [solarmd-pty-ltd/myPower24-WEB#157]
On doing direct comms with the Deye inverter, the 14.3kWh battery shows controlled device comms fail on the BMS, although the inverter picks up comms. Cables have been checked; termination switches are correct. Clients complaining about warning that does not want to clear.

BMS Hardware 301
Firmware version: 183
Inverter type: SUN-8K-SG01LP1-EU
Controlled device update delay: 100
![image](https://user-images.githubusercontent.com/104187532/201886090-c00e4204-29df-4ff8-bca5-8f15602af587.png)
![image](https://user-images.githubusercontent.com/104187532/201886146-fafd266a-ea89-4cf3-ad89-9746aa9afe6b.png)
![image](https://user-images.githubusercontent.com/104187532/201886192-58ebeea4-4588-465c-bc40-d0458f102232.png)

**Comment by platar86** [comment]
Hi @Maritha-v-Loggerenberg , this is inverter specific issue which we are aware of. There is a simple solution to fix it, by not listening to the inverter at all, and never throwing this warning, but then it will be more difficult for the installer to trace issues. We will put setting for coms monitor, and make it disable by default.

**Comment by platar86** [comment]
Setting is available from version 185

**Comment by Maritha-v-Loggerenberg** [comment]
Thank you for the reply. When will version 185 be available? The clients are very unhappy with us right now.
