### ISSUE TITLE
SMA- direct comms warning: "Remote device warning number 1. Specific to connected control device"

### ISSUE THREAD

**Issue by Maritha-v-Loggerenberg** [solarmd-pty-ltd/myPower24-WEB#160]
We have found a warning on a 14.3 kWh battery connected to a SMA inverter: "Remote device warning number 1. Specific to connected control device"

NOTE: we have received this warning on several SMA - 14.3kWh connections.

1. How do we help the client clear this warning in the following circumstances:
 (a) with the presence of a logger?
 (b) in absence of a logger?

2. What does this warning mean specifically?

**Comment by platar86** [comment]
Hi @Maritha-v-Loggerenberg , warning 1 means that the inverter is not set for lithium battery. Please verify if this is correct with your installation.

**Comment by Maritha-v-Loggerenberg** [comment]
Hi @platar86 , will have to check with the installers again.  They said they did put it on Li-mode, but we usually take that with a grain of salt.

**Comment by Maritha-v-Loggerenberg** [comment]
![image](https://user-images.githubusercontent.com/104187532/203947033-4dfc5785-9ca8-42b5-9e56-3b71c7427530.png)
Hi @platar86 It is indeed set to lithium mode.

**Comment by platar86** [comment]
I cannot share full document with you about SMA communication because it is
confidential but small snippets:
[image: image.png]
[image: image.png]
basically, that inverter does not use external BMS information. That is why
the warning is there. I will recommend SI firmware update at least.
Is this a single case ?

**Comment by Maritha-v-Loggerenberg** [comment]
Hi @platar86, not a single case no, but not a lot of people do SMA, it has become an issue with one particular site with 50 batteries connecting to SMA.

We will ask the installers to do an SI update for future sites.
