### ISSUE TITLE
Energy Usage chart logic incorrect in some cases

### ISSUE THREAD

**Issue by henry-thomas** [solarmd-pty-ltd/myPower24-WEB#162]
Example logger: SLV201746805

Grid energy is 0kWh for the daily energy, but displays a value of Grid: 1.9kWh that went to load. This is incorrect, because the energy should have come only from PV or BatDischarge. 

![image](https://user-images.githubusercontent.com/60350870/204743650-b5819ef7-477a-4c40-86ef-2fd90f7b814d.png)

Issue is probably in javascript logic when calculating which energy comes from which source. Around here in energyUsageChart.js:

![image](https://user-images.githubusercontent.com/60350870/204743876-3e44a03e-5f46-4abe-b951-4d851e967d19.png)

**Comment by BrilliesNate** [comment]
Fixed.
