### ISSUE TITLE
BMU-H17 - Intermittently rebooting 

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#165]
Hi,

There is still an intermittent issue with BMU-H17, fw.158 whereby the BMU reboots itself under normal operation. The SoC then halves itself.

I've also noticed this then turning the isolator ON, the BMU will reinitialize the BMSs and then close the relay.

SoC was 57% before it reset.
![image](https://user-images.githubusercontent.com/72873730/205638680-385fb0c6-cc51-4505-b585-3ebb3b289db1.png)

![image](https://user-images.githubusercontent.com/72873730/205638795-8094edfe-5cb8-429c-bd95-58ebd572fc62.png)

**Comment by Kyle-Swanepoel** [comment]
BMU's reset twice this evening, SoC dropped to ~32% both times.

![image](https://user-images.githubusercontent.com/72873730/206002093-ad4aa64e-ad42-4f74-90dd-8e6678005663.png)
![image](https://user-images.githubusercontent.com/72873730/206002167-1a5b5dab-0aa2-484b-95ef-1b7b9b4d2d25.png)

**Comment by platar86** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/11694575/206850814-b7bf3c5c-0a8b-4749-9878-f7c6ff517cdf.png">
none of our BMU in the factory reboots? I need more info, Site configuration and any patterns when the reboot happens. Bussy building something to catch this event in the log

**Comment by Kyle-Swanepoel** [comment]
@platar86 What we have noticed is that most of the battery modules have v301 BMSs. The other sites with BMU-H17 have v304 BMSs. Can we test this in the factory on v301 BMSs?

**Comment by platar86** [comment]
Please close if this issue is resolved or comment further.

**Comment by Kyle-Swanepoel** [comment]
Resolved, client caused the issue by powering the logger from one of the module bus bars.
