### ISSUE TITLE
Cweb issues - Jan 2023 - List

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#169]
Hi Henry,

I'm leaving a list of the issues here that we pick up as we go.

**Comment by Kyle-Swanepoel** [comment]
Advanced User > User list. Not working

![image](https://user-images.githubusercontent.com/72873730/211727133-8ec97ee6-c6c4-4480-8b46-4de2b2d5af27.png)

**Comment by Kyle-Swanepoel** [comment]
Advanced User > Device Search. Not working

![image](https://user-images.githubusercontent.com/72873730/211727212-641e341b-6d87-4c29-971f-5d055c380f34.png)

**Comment by Kyle-Swanepoel** [comment]
Admin User > Logger Updates

Updates not working for loggers, BMSs, BMUs etc.

![image](https://user-images.githubusercontent.com/72873730/211727511-b4fc9451-8efd-48a9-bd57-0bf77253a28a.png)

**Comment by Kyle-Swanepoel** [comment]
Sunsgrow SC HV Series Eth devices have become Solplanet

Logger myPower > Interfaces > eth0 / Ethernet local

![image](https://user-images.githubusercontent.com/72873730/211728135-ab4b24f1-e199-4aa4-bc4b-02f838070c39.png)

![image](https://user-images.githubusercontent.com/72873730/211728180-bf25f3bd-746c-45fb-a1f7-af1095f932d0.png)

**Comment by henry-thomas** [comment]
Will get to device search, can we make that a separate issue please? 

All the rest here is done. If there is anything else, let's make them separate issues so we can close them one by one please.
