### ISSUE TITLE
Carlo Gavazzi EM500 series meters - To be integrated

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#171]
Can we please integrate the EM500 series Carlo Gavazzi meters into the Logger.
We have pressure from Virgin Active for their store roll-out to get this done asap.
Thanks
[EM500_Prtf.pdf](https://github.com/solarmd-pty-ltd/myPower24-WEB/files/10752519/EM500_Prtf.pdf)

**Comment by platar86** [comment]
we need the meter as well sir!

**Comment by Kyle-Swanepoel** [comment]
I will arrange one for you sir
