### ISSUE TITLE
CONHV000139 - Sungrow string inverters - No power type

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#176]
Hi Team,

The Sungrow String inverters are not generating a power type on logger CONHV000139 - Karoo BioScience -
**SLV215521699**.

The actual power is present.

![image](https://user-images.githubusercontent.com/72873730/221569136-f0ea40ac-2d81-438a-a137-bc839bbf0643.png)
![image](https://user-images.githubusercontent.com/72873730/221569149-ef0d2165-bd2a-4413-9ad1-db8d5b37b671.png)

**Comment by henry-thomas** [comment]
Fixed: Power type is set on Sungrow device.
