### ISSUE TITLE
Sungrow SC50HV - executeInstr - not supported - Logger fw. 8.5203

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#178]
Hi Team,

I can't execute instructions on the Sungrow SC50HV on logger firmware 8.5203.

![image](https://user-images.githubusercontent.com/72873730/224693166-e88da201-97a1-45f9-b71b-6852f8d294f3.png)
***
![image](https://user-images.githubusercontent.com/72873730/224693193-3d38ffbc-5c39-4345-9fde-60896356f185.png)

**Comment by henry-thomas** [comment]
Fixed, update on server also has changes now. Still ver8.5203.
