### ISSUE TITLE
"Sunsynk  Time of Use/ Peak Based Filling " buttons do not work

### ISSUE THREAD

**Issue by kamenskiq** [solarmd-pty-ltd/myPower24-WEB#182]
The weekly schedule on and off buttons do not work!
![Screenshot 2023-03-28 090617](https://user-images.githubusercontent.com/70510696/228143495-adb8c893-fef9-4669-8438-b604a82be6f6.png)

**Comment by henry-thomas** [comment]
@kamenskiq Please describe the issue with some details. 

Are there error messages? Logger FW version? What are the symptoms?

**Comment by henry-thomas** [comment]
What model Sunsynk is this?

**Comment by kamenskiq** [comment]
No error mesages, Firmware Ver 106 , Hardware Ver 221. 
When i turn off the button and click on setting the button turns off and turns on by itself.
![Screenshot 2023-03-28 092759](https://user-images.githubusercontent.com/70510696/228147571-0cd82ceb-f4e3-4a81-9434-b4402cdde703.png)

**Comment by henry-thomas** [comment]
Can you confirm that the value is still incorrect after you refresh the page?

**Comment by kamenskiq** [comment]
Yes

**Comment by henry-thomas** [comment]
JS was checking boolean value of "false" as a string value when the component value was changed, so this always resolved to true. 

Fixed.
