### ISSUE TITLE
Override not clearing under certain battery conditions

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#20]
BMS firmware version: 130.
Bootloader version: 103.

Condition: Battery has error 17 (cell overvoltage) and error 29 (open cell detected, due to 1 very unbalanced cell)

Issue:  When  overriding ON for 2 seconds, the BMS closes the relay as expected, however after the 2 sec has elapsed the override status persists, until you manually clear it. The same is true for override OFF.

Notes: Once battery recovered from all errors, the test was performed again and override function worked correctly

![image](https://user-images.githubusercontent.com/72863064/96902991-82148e80-1495-11eb-853f-9803b05bd144.png)

**Comment by platar86** [comment]
To be tested in fw167

**Comment by platar86** [comment]
This issue can not be recreated with normal overvoltage undervoltage error. There is bug fix in the code but it must be revalidated. ver167
