### ISSUE TITLE
Sub device model filter

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#21]
Sub device model filter allows you to check multiple boxes but only applies the filter to the last selected sub device model.

![image](https://user-images.githubusercontent.com/72863064/97593586-7fbcb200-1a0a-11eb-9668-665e05e19b6a.png)

**Comment by merlobranco** [comment]
The affirmation of tis issue is not accurate, what it does the filter is providing the devices which has an ABR_TRIO_50 OR an AXPERT_KING OR an Axpert, etc.

In the following example, taken from http://login.mypower24.co.za/

We can see we have: 

> 0 loggers with ABB_TRIO_50

![DeviceSearch01](https://user-images.githubusercontent.com/40404781/100587406-31e0e580-32f9-11eb-97b3-1d3a6e120e0b.PNG)

> 81 loggers with AXPERT_KING

![DeviceSearch02](https://user-images.githubusercontent.com/40404781/100587410-32797c00-32f9-11eb-9535-27fb9333d1c4.PNG)

> 716 loggers with Axpert

![DeviceSearch03](https://user-images.githubusercontent.com/40404781/100587413-32797c00-32f9-11eb-965e-e4e254cc099f.PNG)

> 794 loggers with ABB_TRIO_50 OR AXPERT_KING OR  Axpert. 794 loggers that have ANY of the selected sub device models

![DeviceSearch04](https://user-images.githubusercontent.com/40404781/100587418-33121280-32f9-11eb-8d9c-7dfd4d4835ef.PNG)

If the affirmation of this issue were right the filter should return 716 loggers NOT 794 loggers

**Comment by merlobranco** [comment]
I could add an checkbox when is clicked is giving the logger that have ALL the sub devices selected.
So we could retrieve the loggers that have ANY of the selected sub device models OR 
retrieve the loggers that have ALL the selected sub device models

**Comment by Masud-Sonday** [comment]
this would be preferably, thanks

**Comment by merlobranco** [comment]
Already implemented
