### ISSUE TITLE
Carlo Gavazzi ET340 meter Instant Values Total not updating

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#22]
SERIAL: SLV201554232
FIRMWARE: 7.103
=========================
Meter Total Values not updating
![image](https://user-images.githubusercontent.com/4703398/98458042-3e0fd200-2195-11eb-82f0-f16482e5e9b5.png)

**Comment by platar86** [comment]
Logger serial number please

**Comment by tiaanv** [comment]
SLV201554232 | Demo unit ( Old Mutual) Bayside Mall

**Comment by platar86** [comment]
this is preliminary update, we do not include in this versions caching files update. please clear your browser cache manually.

**Comment by platar86** [comment]
Going to remove energy counter for Apparent power and reactive for individual phases since they are calculated. 
![image](https://user-images.githubusercontent.com/11694575/98462153-acb35680-21ba-11eb-8d4d-2632f62926b0.png)

**Comment by tiaanv** [comment]
> this is preliminary update, we do not include in this versions caching files update. please clear your browser cache manually.

Clearing browser cache had no impact on TOTAL VALUES updating.  Individual Phases seem OK form start.

**Comment by platar86** [comment]
please verify 
![image](https://user-images.githubusercontent.com/11694575/98462617-416b8380-21be-11eb-9201-deab1893297f.png)

**Comment by tiaanv** [comment]
My Issue is referring to instant values:
![image](https://user-images.githubusercontent.com/4703398/98462687-c8b8f700-21be-11eb-8922-ea5187ea2666.png)

**Comment by tiaanv** [comment]
I am not sure if this is completed yet, but I have seen correct values at least from FW 7.120

**Comment by Kyle-Swanepoel** [comment]
Hi Tiaan,

Currently values are reporting as follows.  Please confirm you are happy?

![image](https://user-images.githubusercontent.com/72873730/105831600-9786e080-5fcf-11eb-99d1-edf7344c7ef3.png)

**Comment by tiaanv** [comment]
close please
