### ISSUE TITLE
Logger Page Keeps loading energy meter modal box

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#23]
SERIAL:         SLV201554232
FIRMWARE:   7.103

=========================

Navigating to My Devices-> Logger

Brings up Meter as modal, and no other functions can be accessed
Close Button also disabled
![image](https://user-images.githubusercontent.com/4703398/98460574-4aecef80-21ae-11eb-88ea-f85e0d4b34f5.png)

**Comment by platar86** [comment]
@Masud18650 please rise this for high priority for Monday. @tiaanv please do soft reboot to fix it temporary.

**Comment by tiaanv** [comment]
> @Masud18650 please rise this for high priority for Monday. @tiaanv please do soft reboot to fix it temporary.

Will do Reboot, Done

**Comment by tiaanv** [comment]
This is a more serious problem if we have no local access to device, since rebooting remotely becomes a problem

**Comment by Masud-Sonday** [comment]
Issue resolved in logger update version: 7.120
