### ISSUE TITLE
Graph shows nanW between updates

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#24]
SERIAL: SLV201554232
FIRMWARE: 7.103
=========================
The graph shows NanW between updates.  The graph is refreshing every second.  Data from the meter seems to be every three seconds.  Inbetween the data the graph shows "NanW" for Y axis labels.

![image](https://user-images.githubusercontent.com/4703398/98460801-14b06f80-21b0-11eb-8dd1-2848b32434bd.png)

**Comment by platar86** [comment]
@henry-thomas please check if this is not already sort by disabling the test Dummy Data

**Comment by platar86** [comment]
@tiaanv, please confirm if the issue is still present.

**Comment by tiaanv** [comment]
> @tiaanv, please confirm if the issue is still present.

Resolved
