### ISSUE TITLE
Live Graph data seems Randomly generated rather than actual data

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#25]
SERIAL: SLV201554232
FIRMWARE: 7.103
=========================

When viewing the Live Data Graph. The data is not related to actual data, but rather semes randomly generated in a narrow envelope for all entities.

![image](https://user-images.githubusercontent.com/4703398/98460924-22b2c000-21b1-11eb-9257-6946d6916347.png)

**Comment by platar86** [comment]
Fixed.
