### ISSUE TITLE
Minor Typo in Energy Meter - ET340

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#26]
SERIAL: SLV201554232
FIRMWARE: 7.103
=========================
Spelling mistake on meter headings under Device mananager->Actual Data

ISTANT VALUES - > INSTANT VALUES

True for all blocks.

![image](https://user-images.githubusercontent.com/4703398/98462345-78409a00-21bc-11eb-9443-64541b30c381.png)

**Comment by platar86** [comment]
Pending release.  EtEm100Meter.1.0.1.js
