### ISSUE TITLE
Charts (using psManager) does not include calculated power, 

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#28]
Chart must include powerList and calcPowerList from psManager or calcPowerList must be merger to powerList.

in case of merging please verify how dashboard and all other internal functions of psManager will affect this.
![image](https://user-images.githubusercontent.com/11694575/98463084-8ba23400-21c1-11eb-86dd-2f5c6459b404.png)

**Comment by platar86** [comment]
Fixed, New function Callback in psManager "onPowerDataUpdateAll"

**Comment by tiaanv** [comment]
No way to view energy meter "Total" (sum of three phases) in Live Graph.
