### ISSUE TITLE
How to include 3ph Meter (ET340) data on Dashboard

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#29]
SERIAL: SLV201554232
FIRMWARE: 7.103
=========================

Linking Total of 3phase meter does not work.
There is an exisiting Power Calculator that calculates Total Energy from the three individual phases (I did not create it).
Linking the "Total Energy" node to  the "GRID OUT" Node. Renders no Data on the dashboard.

The expected result is that the INSTANT POWER, and TOTAL Energy values are used and displayed on the dashboard for the Utility/Grid Feed:
![image](https://user-images.githubusercontent.com/4703398/98463908-89db6f00-21c7-11eb-96d6-929c2d228572.png)

**Comment by tiaanv** [comment]
:)

I saw.. Great!
![image](https://user-images.githubusercontent.com/4703398/98506042-51896e80-2263-11eb-9140-9710b6027c96.png)

**Comment by tiaanv** [comment]
I can see this was achieved by linking all three phases to the GRID OUT node....  
![image](https://user-images.githubusercontent.com/4703398/98506660-ad082c00-2264-11eb-9097-8a63e74500fe.png)

Is the way it will always be done, or will we eventually have a Node representing the "INSTANT VALUES TOTAL" from the CV 3ph meter?  This makes more sense to me.
![image](https://user-images.githubusercontent.com/4703398/98506732-d5902600-2264-11eb-9e18-996aca38d563.png)

**Comment by platar86** [comment]
In progress ...

**Comment by tiaanv** [comment]
> In progress ...

I can already see that the Meter Value Total is updating
![image](https://user-images.githubusercontent.com/4703398/100315566-80247a80-2fc1-11eb-973b-6bef2013dd20.png)

I can also see a new node under power type indicating Total power.  However, linking it to Grid out does not render values on the dashboard.  I know I am jumping the gun. Not expecting it to be complete.  Just giving running feedback.

**Comment by Kyle-Swanepoel** [comment]
Hi Tiaan,

Current progress - Power type calculations are reflecting correctly on the dashboard.  The 3 phases are added together under a new type (Total Power).

![image](https://user-images.githubusercontent.com/72873730/105832133-3c092280-5fd0-11eb-9271-fe5c5ca8bd35.png)

![image](https://user-images.githubusercontent.com/72873730/105832143-40354000-5fd0-11eb-8cea-507c0fdf5acb.png)

**Comment by platar86** [comment]
@Kyle-Swanepoel , please close id sorted
