### ISSUE TITLE
Unable to set Plant Address

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#31]
SERIAL: N/A
FIRMWARE: VARIOUS
=========================
The following dialog is shown indicating google maps API issue
![image](https://user-images.githubusercontent.com/4703398/98497924-26485480-224e-11eb-8dc4-e84c5ced6901.png)
When searching for a location, no matter what is entered the following dialog is shown
![image](https://user-images.githubusercontent.com/4703398/98498077-88a15500-224e-11eb-9074-4df9e351b8b4.png)
The map itself shows "for development purposes only"
![image](https://user-images.githubusercontent.com/4703398/98498093-922abd00-224e-11eb-9d59-3288c6f519b5.png)

**Comment by tiaanv** [comment]
related to #33 
This is now working.

**Comment by Kyle-Swanepoel** [comment]
* Address map working.

![image](https://user-images.githubusercontent.com/72873730/98542439-992aed00-2299-11eb-8503-0a7272e3b8c8.png)

* Full overview logger map working

![image](https://user-images.githubusercontent.com/72873730/98543039-8a910580-229a-11eb-80fc-75e405b9cd19.png)
