### ISSUE TITLE
Logger Map not working (specific user)

### ISSUE THREAD

**Issue by tiaanv** [solarmd-pty-ltd/myPower24-WEB#32]
When logging in as the following user:

OMF | omfportal@micasa.co.za | 11/05/2020 16:05:40by: SolarMD_Support | Enabled | 18 | Super user

The Loggers Map fails to load/Display at all.

This could be due to no valid GPS data for the loggers (related #31 )

**Comment by tiaanv** [comment]
Seems that when the loggers have invalid address/GPS details the Map fails to load.... I updated all the loggers in the profile, and the map loaded successfully.

**Comment by platar86** [comment]
@Kyle-Swanepoel , please do not ignore this issue!

**Comment by Kyle-Swanepoel** [comment]
* Logger with incorrect address - defaults to current address (Map functional).

![image](https://user-images.githubusercontent.com/72873730/98542172-2faade80-2299-11eb-9abb-2bb871638a26.png)

***

* Address option pulls through when typing the name.

![image](https://user-images.githubusercontent.com/72873730/98542328-6680f480-2299-11eb-8b20-304f66699d84.png)

***

* Correct address 

![image](https://user-images.githubusercontent.com/72873730/98542439-992aed00-2299-11eb-8503-0a7272e3b8c8.png)

***

Potential bug - Does not force valid address to be entered but does require a character input to save.

**Comment by tiaanv** [comment]
When setting up site General details for the first time, the map does not work, due to no entry in the "Installation address" entering any value in there does not follow the normal search operations, and does not update the map.  However.  Typing in Anything.  Then refreshing the page will allow for normal functionality (expected behavior) to resume.  Most likely just requires an elegant catch for initial null value.

**Comment by BrilliesNate** [comment]
HI @Kyle-Swanepoel  as discussed, all features are fixed and working.
