### ISSUE TITLE
Logger update 7.120 - Old loggers - No RS232 interface

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#36]
Hi there,

The older loggers eg. b8:27:eb:85:b3:a6 have lost their RS232 interface since the 7.120 update.

![image](https://user-images.githubusercontent.com/72873730/100050649-8e886000-2e22-11eb-865a-f91d0992d0d9.png)
![image](https://user-images.githubusercontent.com/72873730/100050699-a364f380-2e22-11eb-8023-593019afb0e8.png)
![image](https://user-images.githubusercontent.com/72873730/100050734-bf689500-2e22-11eb-9c79-72fc035dc299.png)

**Comment by Masud-Sonday** [comment]
Issue resolved in logger firmware version 7.121
