### ISSUE TITLE
Dashboard values incorrect - Axpert Ai

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#37]
Hi team,

Having issues on Axpert Ai reporting incorrect values (inflated) to what the actual data is.

SLV208782150

![image](https://user-images.githubusercontent.com/72873730/99968921-753fcf00-2da2-11eb-9e6e-f3e57bcff966.png)
![image](https://user-images.githubusercontent.com/72873730/99968929-796bec80-2da2-11eb-91fc-cad344ef19b9.png)
![image](https://user-images.githubusercontent.com/72873730/99968935-7bce4680-2da2-11eb-998f-23330a68da91.png)
![image](https://user-images.githubusercontent.com/72873730/99968945-7ec93700-2da2-11eb-9e56-e5bc717af198.png)

![image](https://user-images.githubusercontent.com/72873730/100052812-5afc0480-2e27-11eb-9076-8185968b8576.png)

![image](https://user-images.githubusercontent.com/72873730/100053077-f8efcf00-2e27-11eb-8ba2-1f7b763a5b61.png)

**Comment by Masud-Sonday** [comment]
Issue fixed in logger update version: 7.122
