### ISSUE TITLE
Logger - Static IP

### ISSUE THREAD

**Issue by SipheloSkepe** [solarmd-pty-ltd/myPower24-WEB#39]
Hi Team, 

We are requiring the functionality to set a static IP address for the network adapters on the logger. Currently this is not working.

This also forms part of a requirement for the Micasa project due to the restrictive nature of the networks in the banking sector.

**Comment by Kyle-Swanepoel** [comment]
Issue opened by Kyle Swanepoel

**Comment by Kyle-Swanepoel** [comment]
![image](https://user-images.githubusercontent.com/72873730/100220337-df31b300-2f1f-11eb-9b9b-eec54832c84c.png)

Functionality is working.

Steps required to set static IP for Eth0 interface.

Connect to logger locally via WiFi or Eth1>
My Devices>
Logger mypower>
Network>
Eth0>
TCP/IP ADDRESS:  > Static >
TCP IP Info > Static > Enter IP (Adapter static configuration) >
Save >

![image](https://user-images.githubusercontent.com/72873730/100221091-e1e0d800-2f20-11eb-8d05-b613d804fbc6.png)

To confirm after reboot, connect Ethernet cable to Eth0 to see network configuration.
