### ISSUE TITLE
SunSpec inverters not working - Logger 7.122

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#40]
Hi team,  

SunSpec inverters not working via Eth0/1.  The device shows as offline on My Devices.  If removed from Interfaces it cannot be added again.

![image](https://user-images.githubusercontent.com/72873730/101017478-d28e0a00-3572-11eb-8806-7c5b0e9e52f0.png)

**Comment by Masud-Sonday** [comment]
Devices are working as the power and energy they produce is visible in the charts ''My Charts'' tab . 
Issue is the device is shown as offline in ''My Devices'' tab.

**Comment by platar86** [comment]
@henry-thomas Kamen will connect one SS inverter for you to test.
