### ISSUE TITLE
SMA SunnyIsland Bridge - Battery Under voltage errors - URGENT

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#42]
Hi team,

We have an issue with SMA SunnyIsland bridge on the loggers.  Ping to the SI is missing and causing a discrepancy between the data we are sending and the data we are receiving from the SI.  We have an increase in the number of support calls for batteries over or under discharging. 

A reboot of the logger temporarily fixes the issue, but the ping soon disappears.  It seems that some of the sites are even working on Lead Acid Emulation, but this was not a change made by us.

![image](https://user-images.githubusercontent.com/72873730/101635701-fea60100-3a32-11eb-882c-4e0f1bca973d.png)
![image](https://user-images.githubusercontent.com/72873730/101635718-02d21e80-3a33-11eb-8d3e-c3d0fa788cb9.png)
![image](https://user-images.githubusercontent.com/72873730/101635728-0796d280-3a33-11eb-8052-21e982591da5.png)

**Comment by LeonidasHanos-debug** [comment]
Hi team, 

The main issue is that the SI are going into a fault state due to battery under/over voltage errors, there are no corresponding errors on mypower24.

There currently are 3 x sites that are reporting the same issue.

SLV200956309 - Bridging technology
SLV201502890 - Kobus
SLV209980540 - Material boards main
SLV210690625 - Material boards extension cluster
SLV212286807 - Leonhard Eins 
SLV210010492 - Leonhard Eins
SLV207265502 - Leonhard Eins


![image](https://user-images.githubusercontent.com/72872833/102106866-c12de300-3e39-11eb-8855-a93d55d500d7.png)

**Comment by Masud-Sonday** [comment]
Ping missing fixed in version 7.1241 logger update.

**Comment by Kyle-Swanepoel** [comment]
@Masud-Sonday Hi Mas,

We have clients reporting daily that their SMA sites are switching off due to Battery under voltage readings on SI.  There are still problems with Nkau, please see excerpt from Sunny Portal.

![image](https://user-images.githubusercontent.com/72873730/106095926-54e31680-613d-11eb-8948-f33abe3e8203.png)

Further issues on this off grid site: (Access has been granted on portal - Plaas Krige)
![image](https://user-images.githubusercontent.com/72873730/106096031-73e1a880-613d-11eb-94c3-ff7b22edaca5.png)
Waiting on 2nd logger to update to 7.1241
![WhatsApp Image 2021-01-27 at 21 43 42](https://user-images.githubusercontent.com/72873730/106096120-9b387580-613d-11eb-985f-b37a7dbed377.jpeg)
![WhatsApp Image 2021-01-27 at 21 43 28](https://user-images.githubusercontent.com/72873730/106096121-9c69a280-613d-11eb-8ad8-9499451da5bd.jpeg)
![WhatsApp Image 2021-01-27 at 21 38 59](https://user-images.githubusercontent.com/72873730/106096127-9d023900-613d-11eb-8e2f-3e2df73963f2.jpeg)

## At the moment, logger soft reboot is still switching the SI off on most sites.

**Comment by Masud-Sonday** [comment]
@Kyle-Swanepoel Sunny island issues fixed in logger update version: 7.191
- Ping Missing
- 6609 Battery Under voltage
- 9331 Meas. range violation battery voltage in device at L1
