### ISSUE TITLE
Axpert MKS 2 

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#43]
Hi team,

As discussed with Masud.

PV calculation is not correct on the Axpert MKS 2 units.  

Another issue we have picked up on Axpert Ai is a discrepancy between the Total Set Charging Current on individual inverters vs the value on the cluster - examples attached.  A soft reboot of the logger sometimes rectifies this. (Kuru 6.png)

https://drive.google.com/drive/folders/1K_n7jU5waPI4yg8Xuye_VZw8OoorCU5H?usp=sharing

**Comment by Kyle-Swanepoel** [comment]
If charging amperage exceeds 60A per inverter, the inverter defaults to 10A max charging.

**Comment by platar86** [comment]
> Hi team,
> 
> As discussed with Masud.
> 
> PV calculation is not correct on the Axpert MKS 2 units.
> 
> Another issue we have picked up on Axpert Ai is a discrepancy between the Total Set Charging Current on individual inverters vs the value on the cluster - examples attached. A soft reboot of the logger sometimes rectifies this. (Kuru 6.png)
> 
> https://drive.google.com/drive/folders/1K_n7jU5waPI4yg8Xuye_VZw8OoorCU5H?usp=sharing

About this, the inverter settings are 10A resolution except first one that is 2A, so if you have to set cluster current of 99A the first possible value that can be assigne is 90A, cluster is not allowed to round up

**Comment by platar86** [comment]
> ng amperage exceeds 60A per inverter, the inverter defa

Please explain this in details
