### ISSUE TITLE
Axpert King - PV not displaying

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#44]
Hi team,

PV value not displaying for Axpert King on the dashboard.  PV is also noted as "false" under OPERATING on the inverter.

Please look into this.

Thanks

![image](https://user-images.githubusercontent.com/72873730/104417237-b9b74200-557d-11eb-8601-80429011ac96.png)
![image](https://user-images.githubusercontent.com/72873730/104417253-be7bf600-557d-11eb-9e98-c79847df5d6f.png)
![image](https://user-images.githubusercontent.com/72873730/104417272-c50a6d80-557d-11eb-86d3-2db7f61ebdca.png)
![image](https://user-images.githubusercontent.com/72873730/104417293-ca67b800-557d-11eb-887e-f9d59e3c702e.png)

**Comment by platar86** [comment]
@Masud-Sonday you can test this with our UPS inverter, please propose solution based on protocol instructions or calculation.

**Comment by henry-thomas** [comment]
Fixed with logger version above 8.220
