### ISSUE TITLE
Logger updates - Proposed scheduling

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#45]
Hi Team,

We have a client - Specialized Solar Systems with more than 200 loggers in the field.  They previously engaged with us in 2019 regarding scheduling updates for the loggers.  Their concern is that they do not have enough data on these sites to accommodate for our updates which happen automatically, causing the loggers to go offline for extended periods of time.

Proposed ideas:
* Scheduling updates for set time periods only eg. 00:00 - 05:00.  
* Ability to turn off automatic updates remotely
* Prompting users of available update for the logger? Including the size of the update required.

I am aware that we can push a new update to selected devices ahead of time, but is it currently possible to withhold a device from updating without locally disabling? 

Thanks
Kyle

**Comment by platar86** [comment]
Blacklist for logger updates introduced .
