### ISSUE TITLE
BMS-EX reporting incorrect Energy rating

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#47]
Hi team,

BMS-EX is reporting the same Energy rating as the Capacity in Ah.
![image](https://user-images.githubusercontent.com/72873730/106098266-67f7e580-6141-11eb-966c-cf019b4ca66e.png)
***
BMS-EM
![image](https://user-images.githubusercontent.com/72873730/106098315-7b0ab580-6141-11eb-9da1-c9358baeb32d.png)
***

**Comment by platar86** [comment]
@Kyle-Swanepoel , please split dashboard from BMS capacity issue

**Comment by platar86** [comment]
Done
