### ISSUE TITLE
Industrial Dashboard does not display battery information

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#49]
Battery data work correclty on the normal dashboard, but if changed to the industrial dashboard the information is not displayed

![image](https://user-images.githubusercontent.com/72863064/106442429-efb45b80-6483-11eb-880f-58c5dd7a631b.png)
![image](https://user-images.githubusercontent.com/72863064/106442528-0955a300-6484-11eb-9976-e053ba001157.png)

**Comment by Kyle-Swanepoel** [comment]
Battery info is now being displayed.  

![image](https://user-images.githubusercontent.com/72873730/128841372-c88fd1c8-f686-4b7b-af76-5aa30981d876.png)
