### ISSUE TITLE
BMS-ex by default should open to the General Info Tab

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#5]
On the mypower24 portal, navigate to ''My Devices'' then BMS-ex.
issue here is the webpage opens to the 9th tab (not available to most)

![image](https://user-images.githubusercontent.com/72863064/96258517-6bb19300-0fbc-11eb-9da4-028da1d3a90a.png)

**Comment by platar86** [comment]
Done
