### ISSUE TITLE
Time of Use table - Logger feature

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#50]
Hi Team,

Please see attached tariff structure for the HV client.

They are requesting a time of use table on the logger to be able to set peak shaving and load shifting based on their needs to the tariff table.

Could we please look into developing such a feature.  Not sure if this should be handled by the inverter itself, or if it can be handled by logger relays.

Thanks
Kyle
![TOU table](https://user-images.githubusercontent.com/72873730/108307769-19c18980-71b7-11eb-9303-614c3984772c.png)

**Comment by BrilliesNate** [comment]
![signal-2021-11-19-085035_001](https://user-images.githubusercontent.com/57934898/142628859-bb96bbed-c22e-41bd-a8bb-809b8059dcd4.png)
@Kyle-Swanepoel  as discussed the component has been built if we ever need it, but the EMS will handle these features anyway.
