### ISSUE TITLE
History Data Missing - October 2020 to April 2021

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#58]
Hi team,

History data is missing on all loggers from 15 October 2020 to 12 April 2021.

Are we any closer to restoring this?  Can we migrate the logger local data onto the server?

![image](https://user-images.githubusercontent.com/72873730/116506506-b726f100-a8bd-11eb-8427-c79a0b7d0eb6.png)
***
![image](https://user-images.githubusercontent.com/72873730/116506527-bf7f2c00-a8bd-11eb-89a7-31a2c2e3f27d.png)

**Comment by platar86** [comment]
@Kyle-Swanepoel , is this issue actual?

**Comment by Kyle-Swanepoel** [comment]
@platar86 it had to do with the data loss when the server was restored in April.  I think we can close this issue.
