### ISSUE TITLE
Logger Local - Update local server version

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#59]
Hi team,

Can we look into updating the Logger local server version to v7.0.8 + to provide a better local monitoring experience for the clients. Currently on v6.1.4 and some of the new devices and features are not supported fully, especially BMS-EX.

![image](https://user-images.githubusercontent.com/72873730/116507058-d4a88a80-a8be-11eb-9ce8-da4a7fbb46c1.png)

**Comment by henry-thomas** [comment]
Closing this issue now. LoggerVWeb updates available for LoggerV version >= 8.401.
