### ISSUE TITLE
Client email database - Mypower24 notifications

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#61]
Hi team,

Can we please implement a feature through Mypower24 that will allow us to send a mass email to our client database.

This would be helpful for server down time notifications or upgrade features etc.

* Exclude users who are not marked as "Active"
* Create a new button that opens an email like window to send to all users
* Allow for Subject line and Body for email
 
![image](https://user-images.githubusercontent.com/72873730/116511001-17ba2c00-a8c6-11eb-9976-23ee6f88b1b6.png)

![image](https://user-images.githubusercontent.com/72873730/116507844-64026d80-a8c0-11eb-8d66-b20ee7d40065.png)

**Comment by platar86** [comment]
@henry-thomas this is already implemented in sense of asking users to revalidate their email. It must be somewhere in LogginCOntroller.java please check if everything is working correct before uploading to server.

**Comment by henry-thomas** [comment]
Added Email Announcement for admin. Users need to opt in first at General Settings -> User Privacy, then they will receive the announcements. 

It also forces users to validate emails before they can opt in.
