### ISSUE TITLE
Goodwe - B30 command (Goodwe internal commands) - Battery force charging from grid

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#62]
Hi Team, 

We are experiencing issues with Goodwe sites where the inverter is receiving a B30 battery force charge command.

SLV206516037 - House Shultze on SEMS portal
SLV214677531 -House Crafford on SEMS portal

@Masud-Sonday has the Goodwe protocol.

Please let us know if you require any further information.

[LV BMS Protocol (CAN) for Solar Inverter Family EN_V1.5.pdf](https://github.com/solarmd-pty-ltd/myPower24-WEB/files/6960403/LV.BMS.Protocol.CAN.for.Solar.Inverter.Family.EN_V1.5.pdf)

**Comment by Kyle-Swanepoel** [comment]
SLV200932377 - SunSynk reporting the same message.  Logger on 7.1933
![WhatsApp Image 2021-06-17 at 17 32 34](https://user-images.githubusercontent.com/72873730/122515433-baad3d80-d00d-11eb-980e-5b6326b329c5.jpeg)

**Comment by LeonidasHanos-debug** [comment]
SLV216387005 - added 5 x sites to SMA bridge as a test.

Still force charging with either bridge.

**Comment by LeonidasHanos-debug** [comment]
SLV211017486 - 3P Sunsynk installation with force charge issue.

![image](https://user-images.githubusercontent.com/72872833/128819498-6e1d82cb-6acc-4906-8c0a-0eb0a980d446.png)

**Comment by platar86** [comment]
Test new bridge and close please. @

**Comment by Kyle-Swanepoel** [comment]
Working well

***

![image](https://user-images.githubusercontent.com/72873730/133766144-ecd855dc-3522-40a3-a090-664445920ab1.png)
