### ISSUE TITLE
Logger e-mail invitation not working

### ISSUE THREAD

**Issue by LeonidasHanos-debug** [solarmd-pty-ltd/myPower24-WEB#63]
Hi Team,

The logger invitation function is not currently working.

The invitation when new accounts are being created are not not received as well as when advanced users invite their clients.

Please look into the issue at your earliest convenience, we are currently manually assisting with new accounts.

**Comment by BrilliesNate** [comment]
![Screenshot 2021-11-18 171306](https://user-images.githubusercontent.com/57934898/142442396-bc7183ba-daed-476c-a01c-55d3ca61eb44.png)
Fixed
