### ISSUE TITLE
Brahman hills - Update

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#64]
Hi team,

Below are a few things to please note that require urgent attention:

Capacity is displaying as 207.36% SoC
BMU v119 - BMS v160

![image](https://user-images.githubusercontent.com/72873730/127632781-a6374db6-30c9-47ea-be17-a38e21eea36b.png)
![image](https://user-images.githubusercontent.com/72873730/127633704-ab7578eb-3494-44d6-a4f8-e404f1f720ce.png)
***

Dashboard

Can the battery graphic be representative of the current capacity.  Currently only shows empty.
Battery SoC (will be fixed with above)
![image](https://user-images.githubusercontent.com/72873730/127635139-bfe76e4a-2e7c-4212-bc28-d1ed3b390fbd.png)

![image](https://user-images.githubusercontent.com/72873730/127634877-4962c51e-889f-45fc-9e0d-6c79d6890575.png)

Many thanks

**Comment by Masud-Sonday** [comment]
Capacity as well as current measuring issue resolved - All BMUs updated to firmware version 134
