### ISSUE TITLE
SunSynk - Force charging from grid

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#66]
Sunsynk single and 3 phase inverters are force charging from grid.  The inverter is receiving a force charge command to charge the batteries.

SLV200932377 - SunSynk reporting force charge message.  Logger on 7.1933

![image](https://user-images.githubusercontent.com/72873730/128840118-8d56cf93-bd3c-48eb-8f1d-996cfdb62189.png)

***

SLV211017486 - 3P Sunsynk installation with force charge issue.

![image](https://user-images.githubusercontent.com/72872833/128819498-6e1d82cb-6acc-4906-8c0a-0eb0a980d446.png)
***
[CAN-Bus-protocol-PYLON-low-voltage-V1.2-20180408.pdf](https://github.com/solarmd-pty-ltd/myPower24-WEB/files/6960398/CAN-Bus-protocol-PYLON-low-voltage-V1.2-20180408.pdf)

**Comment by platar86** [comment]
@Kyle-Swanepoel please close this if its sorted with the new bridge.

**Comment by Kyle-Swanepoel** [comment]
Working well

***

![image](https://user-images.githubusercontent.com/72873730/133772277-fabbe73f-b44f-44d2-9763-0e601daf9a65.png)
