### ISSUE TITLE
Dashboard values exponentially duplicated

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#67]
Dashboard values are exponentially duplicated.  The power types are duplicating themselves on the loggers.

![image](https://user-images.githubusercontent.com/72873730/131812573-e4c7ec09-26f7-4704-a084-cb690bcfe913.png)

**Comment by Kyle-Swanepoel** [comment]
Current list of affected loggers:

SLV207783946 - Jan Griekwastad - resolved
SLV210680831 - Andre HRE Tech
SLV201512555 - David Morrell
SLV206873263 - Dave Boardman
SLV208068963 - Jacques 
SLV214300598  - Werner Terblanche 
SLV211042575    John O' Sullivan
SLV204669928  - Amos pinnicle
SLV210255805 - Kevin Gallagher
SLV208068963  - Jacques 
SLV214355141 - Keegan Bentley 
SLV 201512555  - David Morrell
SLV211147554 - Kate
SLV208068963 - Jacques
SLV205892903 - Somerset West Main (Capitec)
SLV212860145  - 79273 (ICS INSTALL) With Solar

**Comment by platar86** [comment]
temporary fixed, please let us if there is other again. This issue is completely removed in CWEB, but we can not help with the old server.
