### ISSUE TITLE
Cweb - Not picking up individual inverters on Axpert Ai

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#70]
Not picking up individual inverters on Axpert AI

TypeError: Cannot read properties of undefined (reading 'eq')  On deviceConnector 1.1

![image](https://user-images.githubusercontent.com/72873730/133377128-be0a1131-4083-4207-bd00-b5dce20516f1.png)

***

![image](https://user-images.githubusercontent.com/72873730/133377237-3000b7be-1c1b-406e-95fe-a11ce2777c08.png)

***

What we should be seeing

![image](https://user-images.githubusercontent.com/72873730/133377371-efe2f278-a5d6-41a5-bdc7-76fa82f392af.png)

**Comment by platar86** [comment]
@Kyle-Swanepoel  please ask Michael to prepare one board with Voltronik in training room. They are installed already, only need cable tray and cables.

**Comment by platar86** [comment]
this buttons can be replaced with Tab panel

**Comment by platar86** [comment]
![image](https://user-images.githubusercontent.com/11694575/142433130-012d394a-41a9-4b2d-8671-d9d3e38cb6f7.png)
Fixed by someone :)
