### ISSUE TITLE
Axpert King Animation

### ISSUE THREAD

**Issue by henry-thomas** [solarmd-pty-ltd/myPower24-WEB#71]
![image](https://user-images.githubusercontent.com/60350870/133788095-732071bc-47f4-4eab-9533-fc207d6b2a97.png)

**Comment by BrilliesNate** [comment]
![1](https://user-images.githubusercontent.com/57934898/135969379-0eeeae96-2b8a-48eb-9e9a-916432e33618.PNG)


Done.
