### ISSUE TITLE
SMDUIDropDown does not close dropdown when another SMDUIDropDown is selected

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#75]
![image](https://user-images.githubusercontent.com/11694575/135965078-9ec8e547-615e-4d40-9508-cfde2f81416b.png)

**Comment by platar86** [comment]
@BrilliesNate , you fixed the button dropdown already , this should be easy.

**Comment by BrilliesNate** [comment]
Fixed.
