### ISSUE TITLE
Top bar menu color not set @media CSS

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#76]
![image](https://user-images.githubusercontent.com/11694575/136019837-dfb7a90b-f8b9-4216-8fe1-80739192a83f.png)

**Comment by BrilliesNate** [comment]
![22](https://user-images.githubusercontent.com/57934898/136040621-6788a897-1273-46df-97f6-e0ac805f52f9.PNG)
Fixed User @media

**Comment by platar86** [comment]
Thanks Nathan
