### ISSUE TITLE
Cweb - Power types not being generated

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#77]
* live data being populated under Actual Power

![image](https://user-images.githubusercontent.com/72873730/136186805-49f14841-892f-4885-a7ae-1779a4c7ca2e.png)

***

* no power types generated

![image](https://user-images.githubusercontent.com/72873730/136186929-f835b32a-885f-4a67-8e1b-6e0444b66bed.png)

***

* power details empty

![image](https://user-images.githubusercontent.com/72873730/136187336-f1e78693-8b1d-410f-9ebd-101cd4706b01.png)

***

* power calculators pulled through from login.mypower

![image](https://user-images.githubusercontent.com/72873730/136187167-9ed4abcd-d189-4c23-ab48-1995965fa82e.png)

**Comment by platar86** [comment]
fixed
