### ISSUE TITLE
User settings dialog has lower z-index than tab bar -> bmsex

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#79]
![image](https://user-images.githubusercontent.com/11694575/136796677-3a18a368-27db-47d0-aeef-a643826ddec6.png)

**Comment by BrilliesNate** [comment]
![Capture](https://user-images.githubusercontent.com/57934898/136900320-983f61dc-7d0e-4ad9-af48-0a58d83e48b4.PNG)
Fixed, Thanks Kosta
