### ISSUE TITLE
CWEB chart-manager layout topbar button not styled correctly

### ISSUE THREAD

**Issue by platar86** [solarmd-pty-ltd/myPower24-WEB#80]
![image](https://user-images.githubusercontent.com/11694575/137262263-95c767d0-6efc-449d-b099-c03dec5dcc93.png)
please make them same color and button on right side must bi in row not column

**Comment by BrilliesNate** [comment]
![Capture](https://user-images.githubusercontent.com/57934898/137280566-cdfddde1-75b9-42db-b8d9-4115fe6a7a03.PNG)
Fixed.
