### ISSUE TITLE
CWEB --> My Devices --> BMS-Ex --> Settings Advanced -->  Rated Parameters -->  Calibrate Cell Voltage Offset

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#81]
you receive an red balloon if you try set the cell voltage on cell 2.

Message exec fail.
BmsExService exec fail: Value:() not valid number.

![image](https://user-images.githubusercontent.com/72863064/137748988-5ad7270a-7fc3-4df5-813e-a1976e2b651d.png)

**Comment by platar86** [comment]
Done, need server update after 2021-10-27
