### ISSUE TITLE
CWEB -> Logger myPower -> Network

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#83]
Cannot change Function type or TCP/IP ADDRESS function on loggers on CWEB. 

![image](https://user-images.githubusercontent.com/72873730/137918810-a791c2da-3961-4606-ab92-e6bfd004d9a5.png)

**Comment by henry-thomas** [comment]
Fixed: There was an issue with primefaces component, where the items in SelectOneMenu were not initialized until the menu is opened, so this error is thrown. Added patch to mainUtils.
