### ISSUE TITLE
CWEB --> Sub devices --> Multiplies randomly

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#84]
![image](https://user-images.githubusercontent.com/72863064/138261697-7b696835-70bf-4920-8b31-93c18ffa2869.png)
![image](https://user-images.githubusercontent.com/72863064/138261761-af7da3d4-965d-4e55-b793-2eddf47208d7.png)

**Comment by henry-thomas** [comment]
Looks like this is happening when restarting LoggerWS. Looking into it further now.

**Comment by henry-thomas** [comment]
We will clean all duplicates from the database, then see if it happens again. 

We will leave this issue open until we are sure it's stopped.

@Kyle-Swanepoel I'll let you know when we applied the changes to the database.

**Comment by henry-thomas** [comment]
@Kyle-Swanepoel could you please confirm if you know of any cases where there are duplicate subdevices?

**Comment by BrilliesNate** [comment]
HI Team. Have you seen any cases where this happened again. Looks like the fix is working. We just want to confirm if this has happened again.

**Comment by Kyle-Swanepoel** [comment]
Hi Nathan, it looks like it's working on our end. We will reopen the ticket if it occurs again. Thanks

**Comment by BrilliesNate** [comment]
Great, Thanks Kyle.
