### ISSUE TITLE
CWEB --> User profile --> Logger List needs scroller

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#86]
When loggers are more than 12 you cant see the rest - we need pagination or scrolling

![image](https://user-images.githubusercontent.com/72863064/138263477-0862a6af-7abc-4bac-a059-f8139ee71321.png)

**Comment by BrilliesNate** [comment]
![scroller](https://user-images.githubusercontent.com/57934898/138277100-6ae5eaef-d5df-4ed4-84bd-07f907a64fee.PNG)
Added Overflow, thanks Mass
