### ISSUE TITLE
CWEB & Login.mypower  --> My Devices -- Li-ion Storage EX Series --> General Info --> BMS INFORMATION

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#87]
In the BMS information Block if you click on BMS Manufacturer or BMS Manual links, it directs you to a page that says Error 404 - this is true true for CWEB and Login.mypower24.co.za 

![image](https://user-images.githubusercontent.com/72863064/138265170-762c38fa-decd-4366-9927-c2a64f991c81.png)
![image](https://user-images.githubusercontent.com/72863064/138265224-7591a6f6-f655-4a37-9af6-82e53dd2f393.png)
![image](https://user-images.githubusercontent.com/72863064/138265406-35a00ab2-72a8-481f-8191-2e6e67226d43.png)

**Comment by BrilliesNate** [comment]
Fixed: links were pointing to the old website (www.solarmd.co.za), replaced with the new website www.solarmd.com

**Comment by BrilliesNate** [comment]
links open in a new tab.
