### ISSUE TITLE
CWEB --> My Charts --> Power --> Settings --> General -->Cursor

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#88]
CWEB --> My Charts --> Power --> Settings --> General -->Cursor
if Cursor setting is changed from Select X, Select Y or Select XY to None - the selection function continues to work until the page is refreshed

![image](https://user-images.githubusercontent.com/72863064/138272510-051c0375-b066-4382-9878-431a0a370a15.png)
![image](https://user-images.githubusercontent.com/72863064/138272565-b8b7cba3-ebdf-49c5-beb2-2cf458b54dc6.png)

**Comment by henry-thomas** [comment]
Fixed: Only SelectX and SelectXY will create the cards now.
