### ISSUE TITLE
CWEB - My Devices -> AxpertAi -> Settings -> Solar Active/Not Active usage

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#89]
Cannot set values for Solar Active/Not Active usage - The error states the value is not a valid number

![image](https://user-images.githubusercontent.com/72873730/138641311-8c334ae6-392f-4d0c-91f6-cae7638f84da.png)

**Comment by Kyle-Swanepoel** [comment]
It looks like it's only the percentage values that are not working.

Solar ACTIVE Usage:
Solar NOT ACTIVE Usage:

Solar ACTIVE Re-Discharge Threshold:
Solar NOT ACTIVE Re-Discharge Threshold:
Grid Charging Begin Level:  <------------------------------Working
Load Shedding Solar ACTIVE Usage:
Load Shedding Solar NOT ACTIVE Usage:
Load Shedding Solar ACTIVE Re-Discharge Threshold:
Load Shedding Solar NOT ACTIVE Re-Discharge Threshold:
Load Shedding Grid Charging Begin Level:<------------------------------Working
Load Shedding Grid Charging Threshold:<------------------------------Working

Capacity max Diff float Adjust:<------------------------------Working
Min Charge Control Floating:
Slow Charging Begin Setpoint:
Charging Stage End Setpoint:
Fast Charging Stage Max Current:
Slow Charging Stage Max Current:

Grid Emergency Charging Level:
Grid Emergency Charging Threshold:
Grid Cut Off level:<------------------------------Working

**Comment by BrilliesNate** [comment]
![Screenshot 2021-10-27 162318](https://user-images.githubusercontent.com/57934898/139085544-3045e716-4317-4d9c-83ef-192b47e08ccc.png)
Fixed. Changed from a float value to int
