### ISSUE TITLE
Micasa project - Update 2 - Logger options (Logger list)

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#9]
## Proposed portal enhancements

Under this view, settings remain much the same apart from the inclusion of 2 new features.

- History data - Takes the user directly to the History data tab of the logger.  A large feature for the client is the reporting side and having quick access to this is important. 
- [General settings](https://github.com/solarmd-pty-ltd/myPower24-WEB/issues/13) - Easily accessible for the client to update.

https://github.com/solarmd-pty-ltd/myPower24-WEB/projects/2#column-11276887

![image](https://user-images.githubusercontent.com/72873730/96421746-6d1acf80-11f7-11eb-95da-4d68a6be01c2.png)

**Comment by Masud-Sonday** [comment]
@tiaanv We prefer to keep the contents menu simple and small for the purpose of viewing on smaller devices such as mobile.
Please consider using the the ''Set as current'' button, then navigating to the required page.

**Comment by tiaanv** [comment]
@Masud-Sonday. I can accept this as per your comment, and since I have been using the portal now, I also agree with this approach. I actually cannot recall this specifically in our requirements to be in this format.

**Comment by merlobranco** [comment]
@Masud-Sonday @platar86 as discussed yesterday the following direct links where in deviceMonitor and deviceSearch views were created
![Direct Links](https://user-images.githubusercontent.com/40404781/105991435-6defb700-60ac-11eb-8371-921933eea8e1.png)
