### ISSUE TITLE
ATESS HPS inverter stays offline when inverter restarts

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#90]
if ATESS HPS inverter is switched off and then on again - it stays offline on the logger unless the logger is rebooted

![image](https://user-images.githubusercontent.com/72863064/138706184-0d297d3a-ea13-43e9-a187-f225144726a3.png)

**Comment by platar86** [comment]
Tested, Atess coms timeout time increased
