### ISSUE TITLE
CWEB --> Advanced User --> Logger List --> Set as current

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#91]
when right clicking on a logger from Logger list  and selecting ''Set as current'' nothing happens

![image](https://user-images.githubusercontent.com/72863064/139240195-b4912991-a4bd-44f9-b389-e42feb39b250.png)

**Comment by platar86** [comment]
if you refresh the page you will see that is changing. Anyway it`s supposed to give you feedback somehow.

Fixed for refreshing the menu with logger
