### ISSUE TITLE
CWEB --> Advanced User --> Device Search

### ISSUE THREAD

**Issue by Masud-Sonday** [solarmd-pty-ltd/myPower24-WEB#92]
the device filter in Device Search doesnt work

With the devices selected in the picture below the total number of loggers found should be 0 but its 4504

![image](https://user-images.githubusercontent.com/72863064/139241132-a0823f7d-03f3-41f9-95fa-3a4d7344d64f.png)

**Comment by henry-thomas** [comment]
![image](https://user-images.githubusercontent.com/60350870/140891093-4cba8c98-b79d-436f-8c6a-95c1d44d1a4e.png)


Fixed with commit 460aa29137
