### ISSUE TITLE
CWEB -> My Devices -> Logger myPower -> Interfaces -> RS485

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#93]
Scan progress bar not working. Pop-up only displays as below until the scan is complete.

![image](https://user-images.githubusercontent.com/72873730/140268859-4631dea7-268b-4c22-9c7e-619e3acede2c.png)

**Comment by henry-thomas** [comment]
Fixed  with logger update > 8.3151
![image](https://user-images.githubusercontent.com/60350870/140294078-9be9e797-cafc-4d5e-aca7-3140c8dbd134.png)
