### ISSUE TITLE
Login myPower -> My Devices -> Outputs -> Settings

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#95]
Styling issues on the page, not able to easily select the expression you wish to work on.

![image](https://user-images.githubusercontent.com/72873730/141422425-ec7ea7e1-92ec-4cee-9263-e1e5595f3f8b.png)

**Comment by BrilliesNate** [comment]
![Screenshot 2021-11-12 105957](https://user-images.githubusercontent.com/57934898/141439973-4b5c06ef-0d13-41dc-af6c-23e7f5f6499b.png)
Fixed. flex-direction column

**Comment by Kyle-Swanepoel** [comment]
![image](https://user-images.githubusercontent.com/72873730/141445451-342a558d-71e7-4c39-b72b-1da7da276313.png)
Just an example of how it should look

**Comment by BrilliesNate** [comment]
![Screenshot 2021-11-12 130707](https://user-images.githubusercontent.com/57934898/141457543-17bf6381-92dc-4391-bce3-82ad6077fb7a.png)
Fixed. added fontawesome.

**Comment by BrilliesNate** [comment]
![Screenshot 2021-11-12 140306](https://user-images.githubusercontent.com/57934898/141464191-8dcdf23f-09f9-4b7e-b5c1-99cdcb4e5d0b.png)
