### ISSUE TITLE
login myPower -> My Devices -> Axpert -> Settings Advanced

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#96]
The current configuration of the inverters are not being displayed by default

![image](https://user-images.githubusercontent.com/72873730/141434050-b8845178-3537-4bcf-b36b-6cdfac6375a3.png)

**Comment by BrilliesNate** [comment]
![Screenshot 2021-11-17 122913](https://user-images.githubusercontent.com/57934898/142183977-539c573a-66ca-401e-a851-4b2707837ec7.png)
Fixed WidgetVar
