### ISSUE TITLE
Axpert Ai settings - Settings returns error

### ISSUE THREAD

**Issue by KaloyanDi** [solarmd-pty-ltd/myPower24-WEB#98]
![image](https://user-images.githubusercontent.com/47352943/142371333-2c3225c4-e71c-43e8-bb58-f16864cf958e.png)

Axpert Ai > Settings > Load-shedding Mode Settings > Usage to be set as a whole number without decimal.

![image](https://user-images.githubusercontent.com/47352943/142372865-58357e5d-ceaf-478f-8f6a-5120e6f7eff6.png)

Axpert Ai > Settings > Settings used for Dynamic Stage adjustment> Usage to be set as a decimal number for (voltages) incl Settings for Floating stage.

**Comment by KaloyanDi** [comment]
Axpert Ai > Settings > Load-shedding Mode Settings > Usage  returns error when trying to change it

**Comment by platar86** [comment]
![image](https://user-images.githubusercontent.com/11694575/142384510-c1def37e-cb30-4534-8e23-2a646d350832.png)

**Comment by platar86** [comment]
Decimal place issue. Fixed and uploaded.
